### ISSUE TITLE
Rebuilding aws-crt

### ISSUE THREAD

**Issue by zhex900** [electron/electron-rebuild#709] opened 2021-06-08 23:51 UTC
Hi,

I am trying to rebuild `aws-crt` for electron. But no rebuild happened.

```
  electron-rebuild identified prod deps: Set(1) {
  'aws-crt',
  'aws-iot-device-sdk-v2': true,
  'aws-crt': true,

  electron-rebuild scanning: C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\argparse\node_modules +16ms
  electron-rebuild scanning: C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\asn1.js\node_modules +0ms
  electron-rebuild scanning: C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\assert\node_modules +17ms
  electron-rebuild scanning: C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\aws-iot-device-sdk-v2\node_modules +14ms
  electron-rebuild scanning: C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\base\node_modules +0ms
```

Is it because `aws-crt` don't have `binding.gyp` ?

How do I rebuild `aws-crt`?

**Comment by malept** [comment] 2021-06-09 14:26
Duplicate of #268

**Closed by malept** 2021-06-09 14:27 UTC
Labels: duplicate
