### ISSUE TITLE
support new electron version 15.x

### ISSUE THREAD

**Issue by kevinwang930** [electron/electron-rebuild#895] opened 2021-10-15 19:23 UTC
electron version has evolved to 15.x but now electron-rebuild only support up to version 13. Make an new release to support the new electron version seems an easy task. but it has not happened yet. Can anyone kindly explain to me what is the consideration for not doing so ?  electron 15.x has not been proved in the production environment  and may have bugs ?

**Comment by malept** [comment] 2021-11-08 19:00
Duplicate of #886

**Closed by malept** 2021-11-08 19:00 UTC
