### ISSUE TITLE
Make error after using electron-rebuild

### ISSUE THREAD

**Issue by jilieryuyi** [electron/electron-rebuild#622] opened 2021-02-23 22:40 UTC
1、rm -rf node_modules
2、npm install && ./node_modules/.bin/electron-rebuild -d https://npm.taobao.org/mirrors/node -v 11.3.0 -m ./
3、npm run make

Always get the following error， can somebody help? what happened?
If you do not execute electron-rebuildand run make directly, no error will be reported

````
 "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "publish": "electron-forge publish",
    "lint": "eslint src --color",
    "rebuild": "electron-rebuild -f -w ffi-napi"
  },
````

An unhandled rejection has occurred inside Forge:
EPERM: operation not permitted, scandir 'C:\cygwin64\tmp\electron-packager\win32
-x64\docer-win32-x64\resources\app\node_modules\abbrev'
Error: EPERM: operation not permitted, scandir 'C:\cygwin64\tmp\electron-package
r\win32-x64\docer-win32-x64\resources\app\node_modules\abbrev'

**Comment by malept** [comment] 2021-02-23 22:42
Is there a backtrace?

**Comment by malept** [comment] 2021-02-23 22:51
This is a duplicate of https://github.com/electron-userland/electron-forge/issues/2173

**Closed by malept** 2021-02-23 22:51 UTC
Labels: more information needed
