### ISSUE TITLE
Tests fail on windows due to running under bash

### ISSUE THREAD

**Issue by jrobeson** [electron/electron-rebuild#284] opened 2019-03-05 04:12 UTC
This test failure https://travis-ci.org/electron/electron-rebuild/jobs/489788094#L635

```sh
     Error: Could not locate node-gyp
      at Rebuilder.<anonymous> (src\rebuild.ts:232:13)
      at next (native)
      at fulfilled (src\rebuild.ts:4:58)
```

comes from running `yarn install` in an msys based env (bash). It fails to create `.cmd` shims. It does create `.cmd` shims when running under `cmd.exe`

**Comment by jrobeson** [comment] 2019-03-05 04:13
Is there some way to call node-gyp directly? I see that prebuild-install uses the path to the js file directly.

**Comment by jrobeson** [comment] 2019-03-06 23:24
@malept: doesn't #285 just paper over the problem though?

**Comment by malept** [comment] 2019-03-06 23:27
It's a bug in yarn as I see it. I'd be happy to also review a pull request that interacts with `node-gyp` via a JavaScript API, if that's possible.

**Comment by jrobeson** [comment] 2019-03-06 23:47
If i knew how to gaurantee that i'm finding the right node-gyp, then it'd be easy.

**Comment by malept** [comment] 2019-03-06 23:52
I'd imagine it would always use the one that's a dependency of `electron-rebuild`.

**Comment by jrobeson** [comment] 2019-03-07 00:03
but there's no guarantee that it will be at `electron-rebuild/node_modules/node-gyp` or `node_modules/node-gyp`.   I know you can get the real path via `require.resolve()` though, but I don't know how reliable that is in all situations, or whether electron-rebuild ever gets bundled.

**Comment by malept** [comment] 2019-03-07 00:10
It seems to me like you're overthinking it. If there's a problem with module resolution, it's either a bug in the package manager or the bundler you're using.

**Comment by jrobeson** [comment] 2019-03-07 00:14
Indeed, you can't gaurantee that npm will flatten it or not.

**Comment by fortinmike** [comment] 2019-04-24 13:17
I've been having this issue too and noticed that installing any version of `node-gyp` other than `3.8.0` directly in my `electron-rebuild`-using project fixes this. Installing `3.8.0` directly in the same manner causes the bug as before. It seems like `node-gyp` does not install its binary shims properly in `3.8.0`, specifically on Windows as I've not seen this issue with the exact same setup on my Mac.

This seems fixed in node-gyp `4.0.0`. May I suggest upgrading `electron-rebuild`'s `node-gyp` dependency to `4.0.0` to fix this?

**Comment by malept** [comment] 2019-04-25 19:49
> This seems fixed in node-gyp `4.0.0`. May I suggest upgrading `electron-rebuild`'s `node-gyp` dependency to `4.0.0` to fix this?

I tried this in #285. It didn't work, unfortunately: https://travis-ci.org/electron/electron-rebuild/jobs/524626676

**Comment by fortinmike** [comment] 2019-04-25 20:21
Even weirder is that even with node-gyp 3.8.0 it works as expected and generates the shims on my co-worker's PC. I tried to find the root cause on my machine, to no avail. Forcing node-gyp 4.0.0 works, though.

**Comment by malept** [comment] 2019-11-26 19:07
electron-rebuild uses CircleCI and tests are passing on Windows, so I'm closing this.

**Closed by malept** 2019-11-26 19:07 UTC
