### ISSUE TITLE
following README instructions, cannot run electron-rebuild due to lack of module 'bluebird'

### ISSUE THREAD

**Issue by sandover** [electron/electron-rebuild#140] opened 2017-01-06 20:33 UTC
macos 10.12.2
electron 1.4.13

I followed the README's suggested install method:

`» npm install --save-dev electron-rebuild`

This succeeds.  README then advises:
 
*Then, whenever you install a new npm package, rerun electron-rebuild:*
`./node_modules/.bin/electron-rebuild`
 
My actual results:

```
» ./node_modules/.bin/electron-rebuild
module.js:474
    throw err;
    ^

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/[yourname]/src/projectname/node_modules/electron-rebuild/lib/cli.js:8:17)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
```

**Comment by malept** [comment] 2017-01-07 10:46
I think this is a duplicate of https://github.com/electron/electron-rebuild/issues/134. (Which would mean that someone needs to make a patch release of -rebuild.)

**Comment by MarshallOfSound** [comment] 2017-01-07 11:56
@malept I pushed a fix for this but I don't have NPM rights to publish.

Can someone with publish rights send up a new patch version

/cc @electron/maintainers

**Comment by zeke** [comment] 2017-01-09 05:43
I can cut a new release if needed, but will defer first to @paulcbetts.

**Comment by paulcbetts** [comment] 2017-01-09 07:11
Fixed! Sorry about the delay

**Comment by sandover** [comment] 2017-01-10 18:40
It looks like the current version is 1.4.13.  Is there a version roadmap somewhere?

**Comment by malept** [comment] 2017-01-10 18:43
1.4.13 is the [Electron](https://github.com/electron/electron) version. Paul was referring to the `electron-rebuild` version (this project).

**Comment by sandover** [comment] 2017-01-10 22:10
Ah of course, sorry!  :)

**Comment by zeke** [comment] 2017-01-11 01:56
Closing this out. @sandover please let us know if you're still having trouble.

**Closed by zeke** 2017-01-11 01:56 UTC
